### ISSUE TITLE
Failed to execute control_tower lambda

### ISSUE THREAD

**Issue by IvanKr12** [carrier-io/backend_performance#142]
Hey everyone,
I faced issue during starting backend test.
Installation was carried out for local instance according to the instructions.
All containers are fine.

<img width="1631" alt="Screenshot 2024-01-30 at 02 15 44" src="https://github.com/carrier-io/backend_performance/assets/158110808/c3d8156a-8b05-4261-b236-d225ce5d26f4">

Loki error:
`Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/interceptor-1.0.0-py3.6.egg/interceptor/run.py", line 137, in execute_lambda LambdaExecutor(task, event, galloper_url, token).execute_lambda() File "/usr/local/lib/python3.6/site-packages/interceptor-1.0.0-py3.6.egg/interceptor/lambda_executor.py", line 39, in execute_lambda environment=env_vars) File "/usr/local/lib/python3.6/site-packages/docker-3.6.0-py3.6.egg/docker/models/containers.py", line 808, in run container, exit_status, command, image, out docker.errors.ContainerError: Command '['lambda.handler', '[{"container": "getcarrier/perfmeter:2.5.5.5", "execution_params": "{\\"cmd\\": \\"-n -t /mnt/jmeter/site.jmx -Jtest_name=Test7 -Jtest.type=default -Jcomparison_db=comparison_1 -Jtelegraf_db=telegraf_1 -Jinflux.host=192.168.1.112 -Jinflux.db=jmeter_1 -Jgalloper_url=http://192.168.1.112 -Jinflux.password=password -Jinflux.port=8086 -Jloki_port=3100 -Jloki_host=http://192.168.1.112 -Jinflux.username=admin\\", \\"cpu_cores_limit\\": \\"1\\", \\"memory_limit\\": \\"1\\", \\"influxdb_host\\": \\"192.168.1.112\\", \\"influxdb_user\\": \\"admin\\", \\"influxdb_password\\": \\"password\\", \\"influxdb_database\\": \\"gatling_1\\", \\"influxdb_comparison\\": \\"comparison_1\\", \\"influxdb_telegraf\\": \\"telegraf_1\\", \\"loki_host\\": \\"http://192.168.1.112\\", \\"loki_port\\": \\"3100\\"}", "cc_env_vars": {"RABBIT_HOST": "192.168.1.112", "RABBIT_USER": "user", "RABBIT_PASSWORD": "password", "RABBIT_VHOST": "carrier", "GALLOPER_WEB_HOOK": "http://192.168.1.112/task/44096b2e-5ec1-487a-977c-0d3779e5726b"}, "bucket": "tests", "job_name": "Test7", "artifact": "site.zip", "job_type": "perfmeter", "concurrency": 1, "channel": "default", "junit": "True", "quality_gate": "True", "save_reports": "True", "email_recipients": "", "test_id": "e8439cdc-6d89-413b-aee2-32956552ab31"}]']' in image 'getcarrier/lambda:python3.7' returned non-zero exit status 1: b"\x1b[32mSTART RequestId: 288bd421-a8b0-1826-6b7a-0fbae9561743 Version: $LATEST\x1b[0m\n[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda': No module named 'lambda'\nTraceback (most recent call last):\n\x1b[32mEND RequestId: 288bd421-a8b0-1826-6b7a-0fbae9561743\x1b[0m\n\x1b[32mREPORT RequestId: 288bd421-a8b0-1826-6b7a-0fbae9561743\tInit Duration: 213.77 ms\tDuration: 7.08 ms\tBilled Duration: 8 ms\tMemory Size: 1536 MB\tMax Memory Used: 17 MB\t\x1b[0m\n"`

Please tell what could be the problem?
Thanks in advance!

**Comment by hunkom** [comment]
Hi @IvanKr12

You need to generate auth token for your project to start a test. You can find instructions at the end of this guide - [https://github.com/carrier-io/carrier-io/wiki/Project-And-Users](https://github.com/carrier-io/carrier-io/wiki/Project-And-Users)

By the way this repository is used for new Carrier platform. If you will have any more issues with Carrier 2.5 please create them for that repo - [Galloper](https://github.com/carrier-io/galloper)

Thanks

**Comment by IvanKr12** [comment]
Hi @hunkom 
Problem solved after generation auth token.
Thanks a lot!
